log_dir: "Checkpoint"
save_freq: 1
device: "cuda"
epochs: 100
batch_size: 64
pretrained_model: ""
train_data: "Data/train_list.txt"
val_data: "Data/val_list.txt"

dataset_params:
    num_mels: 80
    n_fft: 1024
    hop_size: 256
    win_size: 1024
    sampling_rate: 22050
    fmin: 0
    fmax: 8000

model_params:
   input_dim: 80
   hidden_dim: 256
   n_token: 178
   token_embedding_dim: 512

optimizer_params:
  lr: 0.0005
